version: "3"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/docker
    build:
      context: pipeline
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
      - "$PWD/jenkins-war/jenkins.war:/usr/share/jenkins/jenkins.war"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/.ssh/aws-prod:/opt/aws-prod"
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: centos7
    volumes:
      - "$PWD/db-aws-s3.sh:/tmp/script.sh"
    networks:
      - net
  db_host:
    container_name: db
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - "$PWD/db_data:/var/lib/mysql"
    networks:
      - net
  web:
    container_name: web
    image: ansible-web
    build:
      context: jenkins-ansible/web
    ports:
      - "80:80"
    networks:
      - net
  git:
    container_name: git-server
    image: "gitlab/gitlab-ce:latest"
    hostname: "gitlab.local"
    ports:
      - "8090:80"
    volumes:
      - "$HOME/projects/udemy/gitlab/config:/etc/gitlab"
      - "$HOME/projects/udemy/gitlab/logs:/var/log/gitlab"
      - "$HOME/projects/udemy/gitlab/data:/var/opt/gitlab"
    networks:
      - net
networks:
  net:
